### PR TITLE
toggle dark mode

### PR DESCRIPTION
**Pull request by DodyDharma440**
handle toggle light & dark mode
intergrate to localStorage
dark bootstrap theme
dynamic color for svg waves

### CODE REVIEW

**Comment by DodyDharma440** [comment]
Light Mode
image

Dark Mode
image

**Comment by origranot** [comment]
Amazing, Wow!

Can you do the toggle button more bold?

I personally like the actual toggle animation and not just a button.

If you can style the button in a cooler way it will be amazing!

Looks amazing 🤩

**Comment by origranot** [comment]
@DodyDharma440 Any update?

**Comment by origranot** [comment]
@DodyDharma440 👋 

Can you use single quotes instead of double?

**Comment by DodyDharma440** [comment]
> @DodyDharma440 👋
> 
> Can you use single quotes instead of double?

@origranot 👋
sure, I'm done with using single quotes

**Comment by origranot** [comment]
Why the css file is so big?

**Comment by DodyDharma440** [comment]
> Why the css file is so big?

it's a css file for dark theme bootstrap

**Pull request closed without merging**
