### PR TITLE
add view  on github button

### PR DESCRIPTION
**Pull request by sarthakk24**
screencapture-localhost-3000-2022-10-08-18_36_01
screencapture-localhost-3000-2022-10-08-18_35_43
for issue #58

### CODE REVIEW

**Comment by sarthakk24** [comment]
Solved conflicts too

**Comment by origranot** [comment]
@sarthakk24 Amazing!

Do you mind to style it a bit like Github theme: https://github.com/origranot/url-shortener/pull/90

Thank you!

**Comment by sarthakk24** [comment]
sure i'll do it

**Comment by sarthakk24** [comment]
can you give a little clarification on the above

**Comment by sarthakk24** [comment]
oh i understood thnks :)

**Comment by sarthakk24** [comment]
pushed the changes

**Comment by origranot** [comment]
thanks!

**Comment by sarthakk24** [comment]
@origranot  can you add the hacktoberfest-accepted tag to the pull request

**Pull request merged**
