### PR TITLE
Fix: centered input on mobile

### PR DESCRIPTION
**Pull request by JosephSchec**
Hi , I found this repo on reddit , would love to help out and start working on issues. I centered input for mobile  [this](https://github.com/origranot/url-shortener/issues/181) issue.

### CODE REVIEW

**Comment by GuillemPM** [comment]
Thanks! 🔥
Could you fix the conflicts? I'll review it again after that and merge if its OK.

**Comment by origranot** [comment]
@JosephSchec, Thanks!

As @GuillemPM said, there are some changes we did with the UI.

Do you mind fix the conflicts?

**Comment by JosephSchec** [comment]
> @JosephSchec, Thanks!
> 
> As @GuillemPM said, there are some changes we did with the UI.
> 
> Do you mind fix the conflicts?

Ye sorry about that. I can fix them but was [this PR](https://github.com/origranot/url-shortener/pull/199) merged

**Comment by origranot** [comment]
@JosephSchec Just run prettier on your local branch before pushing.
It seems like you are using double quotes instead of single.

**Comment by origranot** [comment]
@JosephSchec Looks like it's throw an error in the build stage.
https://github.com/origranot/url-shortener/actions/runs/3243021132/jobs/5317147610

Do you mind fix this?

**Pull request closed without merging**
