### PR TITLE
Minor ui changes

### PR DESCRIPTION
**Pull request by Jaskaran2**
Added a gradient background and a red background when error occurs
Screenshot 2022-10-08 at 5 28 18 PM

### CODE REVIEW

**Comment by origranot** [comment]
Hey, thank you for your contribution.

I personally think this alert is too bold.

I would prefer the original style.

**Comment by Jaskaran2** [comment]
> Hey, thank you for your contribution.
> 
> I personally think this alert is too bold.
> 
> I would prefer the original style.

Ok no problem, if you feel the background is fine I can raise another pr with just the background.

**Comment by origranot** [comment]
I think we can add some call background (not the default black).

Maybe add some movements of elements in the background? and animations?

**Comment by Jaskaran2** [comment]
> I think we can add some call background (not the default black).
> 
> Maybe add some movements of elements in the background? and animations?

Sure I will try and do the same

**Pull request closed without merging**
