### PR TITLE
enhanced JS code for toggle btn

### PR DESCRIPTION
**Pull request by Dev-Code24**
#80 #22 #54  These were my earlier PRS
I have written a new code for the toggle button
I believe this will be able to merge

### CODE REVIEW

**Comment by origranot** [comment]
Hey, do you mind fix the conflicts?
We just did a huge refactor.

**Comment by Dev-Code24** [comment]
@origranot 
resolved the conflicts

**Comment by Dev-Code24** [comment]
@origranot 
can you pls add the hacktoberfest label

**Comment by origranot** [comment]
@Dev-Code24 Hey!

I checked the PR. the waves css got messy. 

Also you need to store the theme on localStorage.

Do you mind fix it 💯 ?

**Comment by Dev-Code24** [comment]
@origranot 
i didn't edit the animations.css file and it is the file which maintains the waves

**Comment by origranot** [comment]
Can you pull from master again?

Try to run it.

**Comment by Dev-Code24** [comment]
@origranot 
yeah sure wait

**Pull request closed without merging**
