### PR TITLE
feature/typescript-support

### PR DESCRIPTION
**Pull request by nifaliana**
Typescript support made with ❤️
- Rename all .js file to .ts
- Add some types package 
- Init ts config

### CODE REVIEW

**Comment by origranot** [comment]
@nifaliana WOW!

Thank you so much for the PR, very important!

Do you mind fix the little conflict?

**Comment by nifaliana** [comment]
Thanks @origranot 
Can you fix the little conflit directly ( you have the write access)

Just change the 
const APP_PORT = 3000; 
to
const APP_PORT = process.env.PORT || 3000;

**Comment by nifaliana** [comment]
If it's ok for you @origranot  , you can approve and merge it,

**Comment by origranot** [comment]
@nifaliana I changed some of the code.

You can take a look at the new branch, for some reason I can't get it working well.

**Comment by origranot** [comment]
Migrated to Nest.JS.

**Pull request closed without merging**
