### PR TITLE
new-issues-fixed

### PR DESCRIPTION
**Pull request by Dev-Code24**
@origranot 
#88 was my PR

https://user-images.githubusercontent.com/97425135/194712031-c2e02bc9-e1f1-45a5-b962-bf70c568dab7.mov

### CODE REVIEW

**Comment by origranot** [comment]
@Dev-Code24 It looks great! I really want to merge it alreadt.

Just one more fix, we need to indicate the users that it's a dark mode toggle..

Something like this:
https://codepen.io/grapdroad/pen/gOzaXQg

**Comment by Dev-Code24** [comment]
@origranot 
I've done the needed changes

https://user-images.githubusercontent.com/97425135/194715834-1e556d03-7d64-40fa-90e1-4b9c249f271b.mov

**Comment by origranot** [comment]
@Dev-Code24 Hey!

Do you mind fix the issues?

And maybe put the dark mode icons inside the toggle button.
examples:
https://codepen.io/sophiekoonin/details/jOWKvOr
https://codepen.io/gvissing/details/OJvxoJq

**Comment by origranot** [comment]
@Dev-Code24 can you pull from dev and merge?

**Comment by Dev-Code24** [comment]
@origranot 
who is dev?

**Pull request closed without merging**
