### PR TITLE
Multistage build added

### PR DESCRIPTION
**Pull request by detronetdip**
I have added multistage build in the docker file which resolvs #116 

I have removed multiple `COPY` command and added a single one to copy all the `json` files initially. After adding the multi stage build the final size of the image has reduced around 30 to 35 mb.

|  Before | After |
|-----------|--------|
| 415 MB | 372 MB |

### CODE REVIEW

**Comment by detronetdip** [comment]
@origranot  Please review it.

**Comment by origranot** [comment]
@goldenPheonix02 Hey!

We just migrated into Qwik framework 💯 

Do you mind update the PR?

**Comment by detronetdip** [comment]
Will do that shortly

**Comment by detronetdip** [comment]
Hey @origranot I have modified the `Dockerfile` and after modifying the docker file the size of final image has reduced significantly again.

| Before | 1st Modification | Current |
|----------|-----------------------|------------|
| 415 MB | 372 MB | 176 MB |


Please review it now.

**Pull request merged**
