### PR TITLE
Migrate to Qwik ⚡

### PR DESCRIPTION
**Pull request by GuillemPM**
Big PR here 🔥

## Description
Project is now organized in 2 main folders (frontend and backend), where frontend now contains an app built with Qwik ⚡
All information about how to build and run the project can be found in the updated README.md

## Detailed explanation
The frontend is now built as SSG (Static Site Generation) that improves the overall website speed.
Instead of running a Qwik server by itself, the backend (NestJS) is loading the built solution (`/dist` folder) from the frontend and serving both apps (frontend and backend) in one.
It can be easily separated in the future by simply updating the API calls from the frontend and running the Qwik server, removing the static site loading from Nest will be required too.

In case of having any problem deploying to HerokuApp use the following commands with Heroku-CLI:
`heroku config:set NPM_CONFIG_PRODUCTION=false -a url-shortener-live`
`heroku config:set NODE_MODULES_CACHE=false -a url-shortener-live`

## ✍ Main tasks
[✔] Reorganize the project to keep frontend and backend in 1 solution
[✔] Migrate frontend to Qwik
[✔] Add scripts to build and run the whole project
[✔] Add scripts to build and run each app
[✔] Add a .code-workspace file to keep the project view clean.
[✔] Keep compatibility with HerokuApp
[✔] Update README.md

## 👣 Next steps
* Follow best practices in frontend using Qwik
* Update docker build scripts
* Maybe implement a monorepo tool like nx
* Optimize overall architecture

### CODE REVIEW

**Comment by origranot** [comment]
@GuillemPM Amazing!

Do you mind update your PR again?

There are a lot of changes that are not include in your PR (Cache implementation for example).

**Comment by origranot** [comment]
@GuillemPM Thank you so much for the PR!

You contributed a lot for this project, amazing work buddy!
I really liked the way you combined the front and the backend into one deployment. 
Thanks again!

**Comment by GuillemPM** [comment]
> @GuillemPM Thank you so much for the PR!
> 
> You contributed a lot for this project, amazing work buddy! I really liked the way you combined the front and the backend into one deployment. Thanks again!

Thank you sm! I really appreciate your words.

> Is there a way to contact you? 😄

Sure, you can find my LinkedIn in my profile

**Comment by origranot** [comment]
> Sure, you can find my LinkedIn in my profile
I sent you an invitation 🥇

**Pull request merged**
