### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by eduardconstantin**
Fix title spelling
Change gif

### CODE REVIEW

**Comment by origranot** [comment]
@eduardconstantin 

It looks like the repo had a typo, my bad 🤣 

You are more than welcome to change the typo in the code.

shortner --> shortener.

Thank you bud!

**Comment by eduardconstantin** [comment]
> @eduardconstantin
> 
> It looks like the repo had a typo, my bad 🤣 I changed the repo name (shortner --> shortener) You are more than welcome to change all the typos in the code.
> 
> Thank you bud!

So I wrote it right the first time :))

**Comment by origranot** [comment]
> > @eduardconstantin
> > It looks like the repo had a typo, my bad 🤣 I changed the repo name (shortner --> shortener) You are more than welcome to change all the typos in the code.
> > Thank you bud!
> 
> So I wrote it right the first time :))

Correct, I think there are some typos in some places in the code.
You are welcome to fix them in a PR. (also readme title 👍 )

**Comment by eduardconstantin** [comment]
> > > @eduardconstantin
> > > It looks like the repo had a typo, my bad 🤣 I changed the repo name (shortner --> shortener) You are more than welcome to change all the typos in the code.
> > > Thank you bud!
> > 
> > 
> > So I wrote it right the first time :))
> 
> Correct, I think there are some typos in some places in the code. You are welcome to fix them in a PR. (also readme title 👍 )

Done

**Comment by eduardconstantin** [comment]
> > > > > @eduardconstantin
> > > > > It looks like the repo had a typo, my bad 🤣 I changed the repo name (shortner --> shortener) You are more than welcome to change all the typos in the code.
> > > > > Thank you bud!
> > > > 
> > > > 
> > > > So I wrote it right the first time :))
> > > 
> > > 
> > > Correct, I think there are some typos in some places in the code. You are welcome to fix them in a PR. (also readme title 👍 )
> > 
> > 
> > Done
> 
> Great job pal!
> 
> @eduardconstantin Make sure to remove the new gif from your commit.

Should be fine now

**Comment by origranot** [comment]
Please resolve the conflict :)

**Comment by origranot** [comment]
Thank you!

**Pull request merged**
