### PR TITLE
Fixed Invalid URL

### PR DESCRIPTION
**Pull request by Amiyanshu-web**
Fixed Issue: #42
Let me know if any changes need to be done.

### CODE REVIEW

**Comment by origranot** [comment]
Hey, the problem is on the server side as well.

**Comment by Amiyanshu-web** [comment]
> Hey, the problem is on the server side as well.

I think its resolved now. Can you please specify what error are you encountering?

**Comment by origranot** [comment]
@Amiyanshu-web Hey!

Why is the function is in another function?

This is still not working for url's like: youtube.com

**Comment by Amiyanshu-web** [comment]
> @Amiyanshu-web Hey!
> 
> Why is the function is in another function?
> 
> This is still not working for url's like: youtube.com

Yes, but if we add **https://** before the url its working.

**Pull request closed without merging**
