### PR TITLE
Implement NestJS

### PR DESCRIPTION
**Pull request by GuillemPM**
🚀 Implement NestJS as backend framework 🚀

- [✔] Implement NestJS 9.1.4
- [✔] Add support for Typescript (preferred by NestJS)
- [✔] Add types to the whole project
- [✔] Add NestJS API Versioning (Now it's really easy to add different versions of the API. v1, v2...)

I hope this PR will help this project to be easier to maintain and scale, don't forget to add the hacktoberfest tag if you decide to merge the changes! 😊🏆

### CODE REVIEW

**Comment by GuillemPM** [comment]
I'm aware of the conflicts, I'll resolve them and push the changes

**Comment by origranot** [comment]
@GuillemPM Amazing PR!!

There are several things I want to fix before we approve and migrate to Nest.

1. I think we need to implement the cache module in nest to store our created urls.
2. The structure of the files should be like this:
```
- main.ts
- app.module.ts
- app.service.ts
 - shortener
    - shortener.module.ts
    - shortener.service.ts
    - shortener.controller.ts
    - dto
        - DTOS and stuff..
    - next module etc..
    - .
```
3. I think we should move to yarn (smoother)
4. After the will be merged we can work on tests :)

Let me know if you are still want to work on this PR and do those changes.
Thank you so much for your time!

**Comment by GuillemPM** [comment]
> @GuillemPM Amazing PR!!
> 
> There are several things I want to fix before we approve and migrate to Nest.
> 
> 1. I think we need to implement the cache module in nest to store our created urls.
> 2. The structure of the files should be like this:
> 
> ```
> - main.ts
> - app.module.ts
> - app.service.ts
>  - shortener
>     - shortener.module.ts
>     - shortener.service.ts
>     - shortener.controller.ts
>     - dto
>         - DTOS and stuff..
>     - next module etc..
>     - .
> ```
> 
> 3. I think we should move to yarn (smoother)
> 4. After the will be merged we can work on tests :)
> 
> Let me know if you are still want to work on this PR and do those changes. Thank you so much for your time!

Thanks! It's my very first time working with NestJS so any kind of help or advice is welcome.
I think we could leave the Cache module implementation for another PR, maybe someone wants to do it (included me), but I think it will be better to separate them (Single responsability?? 🤣).

Can you give me a little bit more context about the folder structure? As I understand what you want is remove all the export helpers (index.ts) and subfolders like Controllers, Services... right?

**Comment by GuillemPM** [comment]
PR is ready to review again.

About yarn, I would go the same way as the Cache Module, different PR

**Comment by GuillemPM** [comment]
PR is ready to review again.

About yarn, I would go the same way as the Cache Module, different PR

**Comment by GuillemPM** [comment]
> @GuillemPM Hey!
> 
> I reviewed the PR again. I think the API of this controller should be on a different module. Maybe create an API module to expose functions of the shortener service?
> 
> It looks like the controller of the shortener module is a bit useless.

Which controller are you referring to with "the API of this controller"?
Each controller is used to listen HTTP Request Methods.
Shortener controller is listening for POST Requests (/api/v1/shortener)
App controller is listening for GET Request on "/" to render the main page and "/:url" to redirect to the saved link

**Comment by GuillemPM** [comment]
Done!
Thank you :)

**Pull request merged**
