### PR TITLE
Dark mode toggle button 

### PR DESCRIPTION
**Pull request by Dev-Code24**
This toggle button is working well with the waves and everything is in single quotes
hopefully this gets merged 
#39 #22 These were my earlier PRs

### CODE REVIEW

**Comment by origranot** [comment]
Hey, Do you mind fix the conflicts?

**Comment by Dev-Code24** [comment]
@origranot 
yeah I'll fix them in just few minutes,
Don't know where did the conflicts appear again from

**Comment by Dev-Code24** [comment]
Hey @origranot
can you help me resolve the conflict, it cannot be resolved in the web editor and I am very new to this open source environment

**Comment by Dev-Code24** [comment]
@origranot
I  think I'll have to create a new PR because I am not able to resolve the conflict so after  I create a new PR I'll close this PR
Sorry for the troubles

**Pull request closed without merging**
