### PR TITLE
FEAT : added support for links without https attached ,  For Qwik

### PR DESCRIPTION
**Pull request by kiritocode1**
## Changes 😄
---
On  */frontend/src/routes/index.tsx* 
---
```javascript
-74  : old   	
        const { newUrl } = await getShortenUrl(urlInput!.value);
-74 : new       
	const ValidUrl  = RegExp("^https://").test(urlInput!.value)? urlInput!.value : `https://${urlInput!.value}`; 
	const { newUrl } = await getShortenUrl(ValidUrl);
```
---
## Value

 - [x] Allows Users to pass ```xyz.com``` as well as ```https://xyz.com```
 - [x] Hacktoberfest Fixx for http support as well . 😄
--- 
## RULES
 Follow Code OF Conduct of the project 😄
 Does not have any Coputighted material
 Tested the application locally before merging . ❤️
---
Do let me know if some changes are needed , id love to solve some more issues and Follow this project for hacktoberfest 😃

### CODE REVIEW

**Comment by kiritocode1** [comment]
heyy @origranot  , see iff this works , im up for suggestions and would update asap i promise 😄

**Comment by GuillemPM** [comment]
Hey @kiritocode1 
Thanks for submitting your PR. I did some very basic tests and some results are failing.

Check the results here (JS Tab and open console in the bottom):

https://codepen.io/guillempm/pen/GRdwRRw

Could you fix it and update the PR?
Thanks!🙌

**Comment by kiritocode1** [comment]
Heyy @GuillemPM  😄 , yeah i excluded this so later i can raise an issue for others to solve, thought this might be a good first issue. Sorry if there is a problem, ill fixx it right now 🙂 .

**Comment by GuillemPM** [comment]
> Heyy @GuillemPM  😄 , yeah i excluded this so later i can raise an issue for others to solve, thought this might be a good first issue. Sorry if there is a problem, ill fixx it right now 🙂 . 

Thanks! It's better to push the whole issue solved, I'll wait for your update :)

**Review by GuillemPM — CHANGES_REQUESTED** [review]
Regexp failing on:
http://custom.com

Returns: https://http://custom.com

Please, fix it.

**Comment by kiritocode1** [comment]
Changes Incoming , Sorry If I was Late 😭

**Comment by kiritocode1** [comment]
Heyy @GuillemPM  , @origranot  its done just a single issue needs to be fixed  , If you can help me , that would be wonderful  . 
this is the new code that i came up with  -> 
```javascript 
    let ValidUrl = urlInput!.value; 
    //Tests for https  , http and empty string . 
  if (!RegExp("^https://").test(urlInput!.value)  &&  !RegExp("^http://").test(urlInput!.value)  &&  urlInput!.value ) {
    ValidUrl = `https://${urlInput!.value}`; 
  }
  const { newUrl } = await getShortenUrl$(ValidUrl);
```
- but the error im recieving is 👉  *the value of  identifier ("ValidUrl")  can not be changed  once it is captured in scope ($) .* 
 - im new to Qwik and would appreciate if someone could fixx this problem 😄 or tell me a possible fixx , thank you 💯

**Comment by GuillemPM** [comment]
> Heyy @GuillemPM , @origranot its done just a single issue needs to be fixed , If you can help me , that would be wonderful . this is the new code that i came up with ->
> 
> ```js
>     let ValidUrl = urlInput!.value; 
>     //Tests for https  , http and empty string . 
>   if (!RegExp("^https://").test(urlInput!.value)  &&  !RegExp("^http://").test(urlInput!.value)  &&  urlInput!.value ) {
>     ValidUrl = `https://${urlInput!.value}`; 
>   }
>   const { newUrl } = await getShortenUrl$(ValidUrl);
> ```
> 
> * but the error im recieving is 👉  _the value of  identifier ("ValidUrl")  can not be changed  once it is captured in scope ($) ._
> * im new to Qwik and would appreciate if someone could fixx this problem 😄 or tell me a possible fixx , thank you 💯

Thanks! First of all you should merge our latest changes into your branch, as I can see, your branch is not updated.
The method handleShortenerClick$ has been moved to `./frontend/src/components/shortener-input/handleShortener.ts`

**Pull request closed without merging**
