### PR TITLE
Animated background

### PR DESCRIPTION
**Pull request by Jaskaran2**
Adding animation in the background

https://user-images.githubusercontent.com/60808292/194712295-06636558-544f-4711-93d0-674d0e4d5db3.mp4

### CODE REVIEW

**Comment by origranot** [comment]
@Jaskaran2 Thank you!

First, I want to approve the dark theme pr.

**Comment by Jaskaran2** [comment]
> @Jaskaran2 Thank you!
> 
> First, I want to approve the dark theme pr.

Sorry it's not very clear. Are you talking about someone else's PR?

**Comment by origranot** [comment]
> > @Jaskaran2 Thank you!
> > First, I want to approve the dark theme pr.
> 
> Sorry it's not very clear. Are you talking about someone else's PR?

We need to migrate into front framework, than we can reopen this PR.

**Comment by Jaskaran2** [comment]
> > > @Jaskaran2 Thank you!
> > > First, I want to approve the dark theme pr.
> > 
> > 
> > Sorry it's not very clear. Are you talking about someone else's PR?
> 
> We need to migrate into front framework, than we can reopen this PR.

Ok, let me know when to again raise the PR 😊

**Pull request closed without merging**
